name: Build and Deploy Game

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: '4.3.2'

    - name: Install dependencies
      run: |
       haxelib install all
       haxelib install lime

    - name: Compile
      run: |
       haxe build.hxml
      
    - name: Build
      run: |
       haxelib run lime setup
       haxelib run lime build android

    - name: Create artifact
      run: |
       mkdir -p artifacts
       cp export/build/android/bin

    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: game-artifact
        path: artifacts/