name: build

on: [push, workflow_dispatch]

jobs:
	build-android:
		runs-on: ubuntu-latest
		
		steps:
		- name: checkout
		  uses: actions/checkout@v3
		  
		- name: setup haxe
			uses: krdlab/setup-haxe@v1
   		with:
				haxe-version: 4.3.5
				
		- name: install and compile
			run: |
			  mkdir "%HAXELIB_ROOT%"
				haxelib setup "%HAXELIB_ROOT%"
				haxelib install lime 7.9.0
				haxelib install flixel
				haxelib run lime setup
				haxelib run lime build android
				
		- name: upload artifact
		  uses: actions/upload-artifact@v3
			with:
				name: Build Android
				path: export/release/android/bin